// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvnTM7LSfwnhRh9ztZWDxUsYfxjwOugk',
    appId: '1:333143246063:android:9f5a76fd964bb60aa3471a',
    messagingSenderId: '333143246063',
    projectId: 'trello-baaa3',
    databaseURL: 'https://trello-baaa3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trello-baaa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfWX8ZjnJ-sg6jukEgsm7PJxpaJL_flE',
    appId: '1:333143246063:ios:d4bbe8e07eb40cd3a3471a',
    messagingSenderId: '333143246063',
    projectId: 'trello-baaa3',
    databaseURL: 'https://trello-baaa3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trello-baaa3.appspot.com',
    iosBundleId: 'com.example.trelloApp',
  );
}
